name: ${COMPOSE_PROJECT_NAME:-portainer}

networks:
  portainer_net:
    name: public
    external: true

services:
  agent:
    hostname: agent
    image: portainer/agent:${AGENT_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_NAME:-portainer}_agent
    restart: unless-stopped
    profiles:
      - agent
      - full
    expose:
      - 9001
    ports:
      - "${AGENT_PORT_9001:-9001}:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    security_opt:
      - no-new-privileges:true
    networks:
      - portainer_net

  server:
    hostname: server
    restart: always
    image: portainer/portainer-ce:${SERVER_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_NAME:-portainer}_server
    command: -H tcp://agent:9001 --tlsskipverify
    profiles:
      - server
      - full
    ports:
      - "${SERVER_PORT_9443:-9443}:9443"
      - "${SERVER_PORT_9000:-9000}:9000"
      - "${SERVER_PORT_8000:-8000}:8000"
    volumes:
      - ./data:/data
    networks:
      - portainer_net